source 'https://rubygems.org'

gem 'rails', '4.1.8'
gem 'sqlite3'

gem 'haml-rails'
gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'
gem 'dynamic_form'

gem 'jquery-rails'
gem 'rabl'

group :development do
  gem 'byebug'
  gem 'puma'
  gem 'quiet_assets'
  gem 'spring'
end
